website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func


class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    notes = db.relationship('Note')

website/__init__.py
from flask import Flask, render_template, url_for
from flask_sqlalchemy import SQLAlchemy
from os import PathLike

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    
    app = Flask(__name__, static_url_path='/static')
    app.config['SECRET_KEY'] = 'hjshjhdjah kjshkjdhjs'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    app.config['UPLOAD_FOLDER'] = 'static/files'
    
    db.init_app(app)

    from .views import views
    from .pasteBin import pasteBin
    from .fileConverter import fileConverter
    from .numConverter import numConverter

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(pasteBin, url_prefix='/')
    app.register_blueprint(fileConverter, url_prefix='/')
    app.register_blueprint(numConverter, url_prefix='/')

    from .models import User, Note
    
    with app.app_context():
        db.create_all()
    return app


def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database!')

website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, send_from_directory,url_for,current_app
import json
import csv
import os
import csv

views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])
def home():
    return render_template("home.html")


@views.route('/textEditor', methods=['GET', 'POST'])
def textEditor():
    return render_template("textEditor.html")

@views.route('/codeFlow', methods=['GET', 'POST'])
def codeFlow():
    return render_template("codeFlow.html")

@views.route('/encondingTable', methods=['GET', 'POST'])
def encondingTable():
    return render_template("encondingTable.html")


@views.route('/data/<info_type>')
def get_data(info_type):
    if info_type == 'ascii':
        filename = 'ascii.csv'
    elif info_type == 'unicode':
        filename = 'unicode.csv'
    else:
        return jsonify({'error': 'Invalid info_type'})

    csv_path = os.path.join(current_app.static_folder, 'files', filename)

    # Check if the file exists
    if not os.path.exists(csv_path):
        return jsonify({'error': 'File not found'})

    # Read and return the CSV data
    with open(csv_path, mode='r') as file:
        csv_reader = csv.DictReader(file)
        data = [row for row in csv_reader]
    return jsonify(data)

@views.route('/images', methods=['GET', 'POST'])
def images():
    return render_template("images.html")

@views.route('/search', methods=['GET', 'POST'])
def search():
    search_query = request.args.get('q', '') 
    if not search_query:
        search_query = "Search..."

    return render_template("search.html", search_query=search_query)

@views.route('/about', methods=['GET', 'POST'])
def about():
    if request.method == 'POST':
        # Process form data
        message = request.form['message']
        email = request.form['suggestion-email']
        # Check if the CSV file exists, create it if not
        if not os.path.exists("website/static/messeages/notes.csv"):
            with open("website/static/messeages/notes.csv", 'w', newline='') as csvfile:
                csv_writer = csv.writer(csvfile)
                # Add header row if the file is newly created
                csv_writer.writerow(['Email', 'Message'])

        # Add a new row to the CSV file
        with open("website/static/messeages/notes.csv", 'a', newline='') as csvfile:
            csv_writer = csv.writer(csvfile)
            csv_writer.writerow([email, message])

    return render_template("about.html")

website/templates/about.html
{% extends "base.html" %}

{% block title %}About Me{% endblock %}

{% block content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/tooplate-style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/magnific-popup.min.css') }}">

    <head>
        <title>About Me</title>
        
    </head>
    <body>
        <div class="tm-container-fluid">
            <section class="tm-site-header tm-flex-center tm-mb-50 tm-bgcolor-1 tm-border-rounded">
                
                <h1 class="my-title">About Me  <i class="fa fa-hand-spock-o"></i></h1>
                <img src="{{ url_for('static', filename='photos/me_2.jpeg') }}" alt="Picture of me" style="width: 320px; height: 320px; object-fit: cover; border-radius: 50%;">

    
            </section>
    
            <section class="tm-about tm-mb-50 tm-p-50 tm-bgcolor-2 tm-border-rounded">
                <div class="tm-about-header tm-flex-center">
                    <!-- Set a specific width and height for the image -->
                    <img src="{{ url_for('static', filename='photos/me.jpeg') }}" alt="Picture of Timmy in park" style="width: 250px; height: 250px; object-fit: cover; border-radius: 50%;">
                    <h2>Timothy Scholtz</h2>
                    <h2>(Aka, me)</h2>
                </div>
                <div class="tm-about-text">
                    <p class="tm-mb-40 my-text">
                        I am a Computer Engineering student at the University at Buffalo. I created this website as a side project with the hope that it could prove useful in getting those small, simple pesky tasks that always seem to pop up, like file conversion or formatting text. I hope it proves useful.
                    </p>
                    <p class="tm-mb-0 my-text">
                        I love technology and solving problems. I'm always looking for cool and interesting projects to work on. You can find out more about me and my work at my personal website at <a rel="nofollow" href="https://tim-s.me" target="_blank">tim-s.me</a>.
                    </p>
                </div>
            </section>
    
            <section class="tm-contact tm-mb-50 tm-bgcolor-3 tm-border-rounded">
                <div class="tm-contact-header tm-flex-center">
                    <img src="{{ url_for('static', filename='photos/me_3.jpeg') }}" alt="Picture of Timmy... agiain" style="width: auto; height: 350px; object-fit: cover; border-radius: 20px 20px 20px 20px;">
                </div>
                <div class="tm-contact-info">
                    <h2 class="my-h2">Contact Info <i class="fa fa-address-card"></i> </h2>
                    <hr class="my-hr">
                    <div class="tm-text-white tm-mb-10">Timothy J Scholtz</div>
                    <div class="tm-text-white tm-mb-10"><i class="fa  fa-university"></i> University: &emsp;<a href="https://www.buffalo.edu/" class="tm-link-white"> University At Buffalo</a></div>
                    <div class="tm-text-white tm-mb-10"><i class="fa fa-envelope"></i> Email:  &emsp;<a href="email:tim.scholtz@outlook.com" class="tm-link-white"> tim.scholtz@outlook.com</a></div>
                    <div class="tm-text-white tm-mb-20"><i class="fa fa-phone"></i> Tel:  &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<a href="tel:716-907-8798" class="tm-link-white">716-907-8798</a></div>
                    <hr class="my-hr">
                    <div class="tm-flex tm-mb-10">
                        <a href="https://www.linkedin.com/in/t-j-scholtz" class="tm-social-link"><i class="fa fa-linkedin-square my-links"></i></a>
                        <a href="https://github.com/t-scholtz" class="tm-social-link"><i class="fa fa-github-alt my-links"></i></a>
                        <a href="https://t-scholtz.github.io/" class="tm-social-link"><i class="fa fa-globe my-links"></i></a>
                    </div>
                    <div class="tm-flex tm-mb-10">
                        <a href="https://www.instagram.com/tiny_treks/" class="tm-social-link"><i class="fa fa-instagram my-links"></i></a>
                        <a href="https://www.youtube.com/channel/UCuToB0y-BPd_TXZwWGiJJOQ" class="tm-social-link "><i class="fa fa-youtube-play my-links"></i></a>
                        <a href="https://open.spotify.com/user/mwk1wzobiq06le7tw3govdzy8" class="tm-social-link"><i class="fa fa-spotify my-links"></i></a>
                    </div>
                </div>
                <div class="tm-contact-form-container">
                    <form id="contact-form" action="{{ url_for('views.about') }}" method="POST" class="tm-contact-form">
                        <div class="tm-mb-30">
                            <textarea rows="10" name="message" class="tm-mb-50" placeholder="Leave a comment, message, or a suggestion" required=""></textarea>
                            <input type="email" name="suggestion-email" placeholder="Your email" required="" />
                        </div>
                        <button type="submit" class="tm-right tm-btn-submit">Send</button>
                    </form>
                </div>
            </section>
            
        </div>
        
        <script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/imagesloaded.pkgd.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/isotope.pkgd.min.js') }}"></script>
        
    </body>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock %}</title>
  <link rel="icon" type="image/png" href="{{ url_for('static', filename='photos/icons8-tree-30.png') }}">

  <!-- Font Awesome CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    crossorigin="anonymous">
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab&display=swap" rel="stylesheet">

  <!-- Bulma Version 0.9.0-->
  <link rel="stylesheet" href="https://unpkg.com/bulma@0.9.4/css/bulma.min.css" />
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/base.css') }}">
</head>

<body>
  <nav class="navbar is-gradient" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        <i class="fa fa-tree"></i> Cedar Tools
      </a>

      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
        data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
      </div>

      <div id="searchWrapper" class="navbar-start">
        <div class="navbar-item">
          <div class="control has-icons-left has-icons-right">
            <div class="search-input">
              <a href="#" target="_blank" hidden></a>
              <input id="searchInput" class="input" type="text" placeholder="Search..." autocomplete="off">
              <div class="autocom-box"></div>
              <div id="searchButton" class="icon"><i class="fa fa-search"></i></div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="navbar-item has-dropdown is-hoverable">
      <a class="navbar-item">
        Menu <i class="fa fa-bars"></i>
      </a>

      <div class="navbar-dropdown ">
        <span class="navbar-item-heading">Unit Conversion</span>
        <a class="navbar-item" href="/baseConverter">
          <i class="fa fa-exchange"></i> Base Converter
        </a>
        <span class="navbar-item-heading">Data</span>
        <a class="navbar-item" href="/encondingTable">
          <i class="fa fa-balance-scale"></i> Encoding Tables
        </a>
        <span class="navbar-item-heading">Test Editing</span>
        <a class="navbar-item" href="/pasteBin">
          <i class="fa fa-paste"></i> Paste Bin
        </a>

        <span class="navbar-item-heading">Info</span>
        <a class="navbar-item" href="/about">
          <i class="fa fa-info-circle"></i> About
        </a>
      </div>
    </div>
    </div>
    </div>
  </nav>

  <main role="main" class="col-md-9 ml-sm-auto col-lg-9 px-4">
    <div class="main">
      {% block content %} {% endblock %}
    </div>
  </main>
  <script src="{{ url_for('static', filename='js/suggestions.js') }}"></script>
  <script src="{{ url_for('static', filename='js/script.js') }}"></script>



</body>

</html>

website/templates/baseConverter.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
    %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/baseConverter.css') }}">

<body>
    <div class="container">
        <div class="heading-box">
            <h1 class="custom-title">Data Tables</h1>
            <h2 class="custom-sub-title"> Whole Numbers</h2>
           
        </div>
        <hr>
    </div>

    <div id="layout">
        

        <div class="slider-container" data-min="0" data-max="2">
            <div class="position-label" style="left: 0%; top: 20px;">Signed</div>
            <div class="position-label" style="left: 50%; top: 20px;">1's Complement</div>
            <div class="position-label" style="left: 100%; top: 20px;">2's Complement</div>
            <input type="range" class="slider" min="0" max="2" step="1" value="0" onchange="updateFromDecimal()">
        </div>

        <div class="slider-container" data-min="0" data-max="3">
            <div class="position-label" style="left: 0%; top: 20px;">8-bit</div>
            <div class="position-label" style="left: 33%; top: 20px;">16-bit</div>
            <div class="position-label" style="left: 66%; top: 20px;">32-bit</div>
            <div class="position-label" style="left: 100%; top: 20px;">64-bit</div>
            <input type="range" class="slider" min="0" max="3" step="1" value="0" onchange="updateFromDecimal()">
        </div>

        <div class="spacer"></div>
    
        <div class="data-container">
            <label class="data-label" >Decimal</label>
            <input class="data" type="text" id="decimalInput" placeholder="Decimal" oninput="updateFromDecimal()">
        </div>
        <div class="data-container">
            <label class="data-label" >Binary</label>
            <input class="data" type="text" id="binaryInput" placeholder="Binary" oninput="updateFromBinary()">
        </div>
        <div class="data-container">
            <label class="data-label" >Hexidecimal</label>
            <input class="data" type="text" id="hexInput" placeholder="Hexadecimal" oninput="updateFromHexadecimal()">
        </div>
    
        <div class="spacer"></div>
        </div>
        <div class="container">
            <div class="heading-box">
                <h2 class="custom-sub-title"> Floating Point</h2>
            </div>
            <hr>
        </div>
        <div id="layout">
        

        <div class="slider-container" data-min="0" data-max="1">
            <div class="position-label" style="left: 0%; top: 20px;">Binary</div>
            <div class="position-label" style="left: 100%; top: 20px;">Hex</div>
            <input type="range" class="slider" min="0" max="1" step="1" value="0" onchange="updateFromReal()">
        </div>

        <div class="spacer"></div>

        <div class="data-container">
            <label class="data-label" >Real</label>
            <input class="data" type="text" id="real" placeholder="Real" oninput="updateFromReal()">
        </div>
        <div class="data-container">
            <label class="data-label" >Float</label>
            <input class="data" type="text" id="float" placeholder="Float" oninput="updateFromFloat()">
        </div>
        <div class="data-container">
            <label class="data-label" >Double</label>
            <input class="data" type="text" id="double" placeholder="Double" oninput="updateFromDouble()">
        </div>
    
    </div>

    <script>

        function updateFromDecimal() {
            const decimalValue = parseInt(document.getElementById('decimalInput').value, 10);

            // Get the slider values
            const unsignedSliderValue = document.querySelector('.slider-container[data-min="0"][data-max="2"] .slider').value;
            const bitSliderValue = document.querySelector('.slider-container[data-min="0"][data-max="3"] .slider').value;

            // Send data to the Flask server
            fetch('/deciUpdate', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    decimalValue: decimalValue,
                    unsignedSliderValue: unsignedSliderValue,
                    bitSliderValue: bitSliderValue,
                }),
            })
            .then(response => response.json())
            .then(data => {
                // Update binary and hexadecimal inputs with the received data
                document.getElementById('binaryInput').value = data.binaryValue;
                document.getElementById('hexInput').value = data.hexValue;
            })
            .catch(error => console.error('Error:', error));
        }

        function updateFromHexadecimal() {
            const decimalValue = parseInt(document.getElementById('hexInput').value, 10);

            // Get the slider values
            const unsignedSliderValue = document.querySelector('.slider-container[data-min="0"][data-max="2"] .slider').value;
          fetch('/hexUpdate', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    hexValue: hexValue,
                    unsignedSliderValue: unsignedSliderValue,
                    bitSliderValue: bitSliderValue,
                }),
            })
            .then(response => response.json())
            .then(data => {
                // Update binary and hexadecimal inputs with the received data
                document.getElementById('decimalInput').value = data.decimalValue;
                document.getElementById('binaryInput').value = data.binaryValue;
            })
            .catch(error => console.error('Error:', error));
        }

        function updateFromBinary() {
            const binaryValue = parseInt(document.getElementById('binaryInput').value, 10);

            const unsignedSliderValue = document.querySelector('.slider-container[data-min="0"][data-max="2"] .slider').value;
            const bitSliderValue = document.querySelector('.slider-container[data-min="0"][data-max="3"] .slider').value;

            fetch('/binUpdate', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    binaryValue: binaryValue,
                    unsignedSliderValue: unsignedSliderValue,
                    bitSliderValue: bitSliderValue,
                }),
            })
            .then(response => response.json())
            .then(data => {
                // Update binary and hexadecimal inputs with the received data
                document.getElementById('decimalInput').value = data.decimalInput;
                document.getElementById('hexInput').value = data.hexValue;
            })
            .catch(error => console.error('Error:', error));
        }

        function updateFromReal(){
            const realValue = document.getElementById('real').value;
            const binOrHex = document.querySelector('.slider-container[data-min="0"][data-max="1"] .slider').value;

            fetch('/updateFromReal', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    realValue: realValue,
                    binOrHex: binOrHex,
                }),
            })
            .then(response => response.json())
            .then(data => {
                document.getElementById('float').value = data.float;
                document.getElementById('double').value = data.double;
            })
            .catch(error => console.error('Error:', error));
        }

        function updateFromFloat(){
            const floatValue = document.getElementById('float').value;
            const binOrHex = document.querySelector('.slider-container[data-min="0"][data-max="1"] .slider').value;

            fetch('/updateFromFloat', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    floatValue: floatValue,
                    binOrHex: binOrHex,
                }),
            })
            .then(response => response.json())
            .then(data => {
                document.getElementById('real').value = data.real;
                document.getElementById('double').value = data.double;
            })
            .catch(error => console.error('Error:', error));
        }

        function updateFromDouble(){
            const doubleValue = document.getElementById('double').value;
            const binOrHex = document.querySelector('.slider-container[data-min="0"][data-max="1"] .slider').value;

            fetch('/updateFromDouble', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    doubleValue: doubleValue,
                    binOrHex: binOrHex,
                }),
            })
            .then(response => response.json())
            .then(data => {
                document.getElementById('real').value = data.real;
                document.getElementById('float').value = data.float;
            })
            .catch(error => console.error('Error:', error));
        }
    </script>
    </body>
    </html>    
    {% endblock %}

website/templates/codeFlow.html
{% extends "base.html" %} {% block title %}Code Flow{% endblock %} {% block
content %}

<link
  rel="stylesheet"
  type="text/css"
  href="{{ url_for('static', filename='css/baseConverter.css') }}"
/>
<script src="{{ url_for('static', filename='js/raphael.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/flowchart.js') }}"></script>

<body>
  <div class="container">
    <div class="heading-box">
      <h1 class="custom-title">Code Flow</h1>
      <h2 class="custom-sub-title">Trace your code structure graphically</h2>
    </div>
    <hr />
  </div>
  <div>
    <textarea id="code" style="width: 100%" rows="11">
    st=>start: Start|past:>http://www.google.com[blank]
    e=>end: End:>http://www.google.com
    op1=>operation: My Operation|past:$myFunction
    op2=>operation: Stuff|current
    sub1=>subroutine: My Subroutine|invalid
    cond=>condition: Yes
    or No?|approved:>http://www.google.com
    c2=>condition: Good idea|rejected
    io=>inputoutput: catch something...|request
    para=>parallel: parallel tasks
    
    st->op1(right)->cond
    cond(yes, right)->c2
    cond(no)->para
    c2(true)->io->e
    c2(false)->e
    
    para(path1, bottom)->sub1(left)->op1
    para(path2, right)->op2->e
    
    st@>op1({"stroke":"Red"})@>cond({"stroke":"Red","stroke-width":6,"arrow-end":"classic-wide-long"})@>c2({"stroke":"Red"})@>op2({"stroke":"Red"})@>e({"stroke":"Red"})</textarea
    >
  </div>
  <div><button id="run" type="button">Run</button></div>
  <div id="canvas"></div>
</body>

<script>
  window.onload = function () {
    var btn = document.getElementById("run"),
      cd = document.getElementById("code"),
      chart;

    (btn.onclick = function () {
      var code = cd.value;

      if (chart) {
        chart.clean();
      }

      chart = flowchart.parse(code);
      chart.drawSVG("canvas", {
        // 'x': 30,
        // 'y': 50,
        "line-width": 3,
        maxWidth: 3, //ensures the flowcharts fits within a certian width
        "line-length": 50,
        "text-margin": 10,
        "font-size": 14,
        font: "normal",
        "font-family": "Helvetica",
        "font-weight": "normal",
        "font-color": "black",
        "line-color": "black",
        "element-color": "black",
        fill: "white",
        "yes-text": "yes",
        "no-text": "no",
        "arrow-end": "block",
        scale: 1,
        symbols: {
          start: {
            "font-color": "red",
            "element-color": "green",
            fill: "yellow",
          },
          end: {
            class: "end-element",
          },
        },
        flowstate: {
          past: { fill: "#CCCCCC", "font-size": 12 },
          current: {
            fill: "yellow",
            "font-color": "red",
            "font-weight": "bold",
          },
          future: { fill: "#FFFF99" },
          request: { fill: "blue" },
          invalid: { fill: "#444444" },
          approved: {
            fill: "#58C4A3",
            "font-size": 12,
            "yes-text": "APPROVED",
            "no-text": "n/a",
          },
          rejected: {
            fill: "#C45879",
            "font-size": 12,
            "yes-text": "n/a",
            "no-text": "REJECTED",
          },
        },
      });

      $("[id^=sub1]").click(function () {
        alert("info here");
      });
    })();
  };

  function myFunction(event, node) {
    console.log("You just clicked this node:", node);
  }
</script>

{% endblock %}

website/templates/encondingTable.html
{% extends "base.html" %} {% block title %}Econding Tables{% endblock %} {%
block content
%}

<head><link rel="stylesheet" type="text/css"
        href="{{ url_for('static', filename='css/encondingTable.css') }}">
</head>
<body>
    <section class="section">
        <div class="container">
            <div class="heading-box">
                <h1 class="custom-title">Data Tables</h1>
                <div class="select">
                    <select id="infoSelect" onchange="loadData()">
                        <option value="ascii">ASCII Table</option>
                        <option value="unicode">Unicode Table</option>
                    </select>
                </div>
            </div>
        </div>

        <div id="dataDisplay">
            <!-- Data will be displayed here -->
        </div>

    </section>
</body>

<script>
    function loadData() {
        var selectBox = document.getElementById("infoSelect");
        var selectedValue = selectBox.options[selectBox.selectedIndex].value;
        var url = "/data/" + selectedValue;
        fetch(url)
            .then(response => response.json())
            .then(data => {
                var table = "<table class='table is-striped table is-hoverable table is-fullwidth'><thead><tr>";
                Object.keys(data[0]).forEach(key => {
                    table += "<th>" + key + "</th>";
                });
                table += "</tr></thead><tbody>";
                data.forEach(row => {
                    table += "<tr>";
                    Object.values(row).forEach(value => {
                        table += "<td>" + value + "</td>";
                    });
                    table += "</tr>";
                });
                table += "</tbody></table>";
                document.getElementById("dataDisplay").innerHTML = table;
            });
    }
    document.addEventListener("DOMContentLoaded", function() {
        loadData();
    });
</script>

{% endblock %}

website/templates/fileConverter.html
{% extends "base.html" %}
{% block title %}File Converter{% endblock %}
{% block content %}

<h1 align="center">File Converter</h1>

<form method='POST' enctype='multipart/form-data'>
    {{ form.hidden_tag() }}
    {{ form.file() }}
    {{ form.submit() }}
</form>

{% if conversion_form.conversion.choices %}
    <form method='POST'>
        {{ conversion_form.csrf_token }}
        {{ conversion_form.conversion() }}
        {{ conversion_form.submit_conversion() }}
    </form>
{% endif %}

{% with messages = get_flashed_messages() %}
    {% if messages %}
        <ul class=flashes>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endwith %}

{% endblock %}

website/templates/images.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
    %}
    <h1 align="center">Awesome Tools</h1>
    <ul class="list-group list-group-flush" id="notes">
      <p>Awesome tools is a collection of tools to formate and edit text, convert files, and more simple but useful feature</p>
    </ul>
    
    {% endblock %}

website/templates/search.html
{% extends "base.html" %} {% block title %}Search{% endblock %} {% block content
    %}
    <head><link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/search.css') }}">
    </head> 
    <body>
        <section class="section">
            <div class="container">
                <div class="search-box" id="searchArea">
                    <h1 class="custom-title">Search</h1>
                    <div class="field has-addons">
                        <div class="control is-expanded">
                            <input class="input" type="text" id="searchBar2" placeholder="Search...">
                        </div>
                        <div class="control" id="searchBar">
                            <a class="button is-info">
                                <span class="icon is-small"><i class="fa fa-search"></i></span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <ul id="searchResultsContainer"></ul>

    <script src="{{ url_for('static', filename='js/search.js') }}"></script>

    </body>
{% endblock %}

website/templates/textEditor.html
{% extends "base.html" %} {% block title %}Text Editor{% endblock %} 
    {% block content %}
    <h1 align="center">Text Editor</h1>

    <!-- Create a container for the text editor -->
    <div id="editor-container">
      <!-- Text area for user input -->
      <textarea id="editor-input" oninput="renderMarkdown()"></textarea>
      <!-- Rendered Markdown output -->
      <div id="markdown-output"></div>
  </div>

  <script >

function renderMarkdown() {
    const userInput = document.getElementById('editor-input').value;
    
    // Use the Markdown library to convert user input to HTML
    const markdownOutput = marked(userInput);

    // Display the rendered Markdown in the output div
    document.getElementById('markdown-output').innerHTML = markdownOutput;

    // You can add additional functionalities here, like spell checking and underlining misspelled words
}

  </script>
{% endblock %}

    